### ISSUE TITLE
Run once?

### ISSUE THREAD

**Issue by dburles** [East5th/package-scan#4]
I think it might make sense to only run once after Meteor is first run and not after each reload. What do you think?

**Comment by pcorey** [comment]
As far as I know, there's no way to determine what is causing the server to start/restart. I don't know how I'd tell if a server was restarted due to source changes, or if a new package was added.

Are you concerned about performance, or are you just annoyed by the messages? You can currently ignore vulnerabilities reported for whole packages, but I was considering making that functionality more fine grained by letting you specify which specific alerts you want to ignore.
