### ISSUE TITLE
_ is not defined

### ISSUE THREAD

**Issue by hems** [East5th/package-scan#8]
https://github.com/East5th/package-scan/blob/9e3587860a23483851b0dd1f8cd3ad8730a67628/lib/package-scan.js#L24

Recently my meteor build started complaining about what i believe to be that line of code?

here is the error:

````bash
packages/east5th_package-scan.js:41
    return _.contains(ignore, package);
    ^

ReferenceError: _ is not defined
    at skipPackage (packages/east5th_package-scan.js:41:5)
    at packages/east5th_package-scan.js:46:13
    at Array.forEach (<anonymous>)
    at Interface.scanPackages (packages/east5th_package-scan.js:45:14)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:368:8)
    at ReadStream.onend (readline.js:147:10)
    at emitNone (events.js:111:20)
    at ReadStream.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
````

**Comment by coagmano** [comment]
Looking at the [`package.js` file](https://github.com/East5th/package-scan/blob/master/package.js#L12), it hasn't defined any dependency on underscore.

Meteor used to make underscore globally available, so many packages (like this one) never bothered to add it to the dependency list. Meteor has since made the change to require that apps and packages should declare all their dependencies, as underscore is being removed from the internals to make it optional and save bundle size.

You can easily fix this in your app by making a local fork (download the package code into a folder in your `/packages` directory of your app) and edit `package.js` to add `api.use('underscore')`

Telling you how to fix it in the assumption the package won't be fixed

**Comment by hems** [comment]
thanks for the detailed explanation @coagmano !

> Telling you how to fix it in the assumption the package won't be fixed

if we're considering the package won't be updated ( and fixed ) then perhaps the best is to actually remove this package from my application and find a newer / maintained package for it...

I just created two patches for the code, just in case the project come back to life ( :

https://github.com/East5th/package-scan/pull/10 and https://github.com/East5th/package-scan/pull/9

**Comment by pcorey** [comment]
Thanks @hems! Your fixes are merged and I just published them in `0.0.7`.

**Comment by hems** [comment]
> Thanks @hems! Your fixes are merged and I just published them in `0.0.7`.

Amazing! Just out of curiosity I can see the alerts are hardcoded here:
https://github.com/East5th/package-scan/blob/master/data/alerts.json and were not updated since 2017..

Is there an updated list somewhere or any plans to update that list?

**Comment by pcorey** [comment]
@hems Yeah, `package-scan` is largely dead. I don't do enough Meteor security work nowadays to actively contribute to the vulnerability collection, and community contributions never really took off.

I'm considering archiving the project.

**Comment by coagmano** [comment]
Add and remove underscore 😂
https://github.com/East5th/package-scan/pull/11

**Comment by StorytellerCZ** [comment]
Would have been easier to remove in the first place since it is only one function that needs it.

**Comment by pcorey** [comment]
Thanks @StorytellerCZ. `0.0.8` is published.
